[project]
name = 'greedo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.NFT_backed_collateral]
path = 'contracts/NFT_backed_collateral.clar'
clarity_version = 2
epoch = 2.5

[contracts.dispute_resolutions]
path = 'contracts/dispute_resolutions.clar'
clarity_version = 2
epoch = 2.5

[contracts.interest_rate_dynamics]
path = 'contracts/interest_rate_dynamics.clar'
clarity_version = 2
epoch = 2.5

[contracts.loan_contract]
path = 'contracts/loan_contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-based]
path = 'contracts/reputation-based.clar'
clarity_version = 2
epoch = 2.5

[contracts.research]
path = 'contracts/research.clar'
clarity_version = 2
epoch = 2.5

[contracts.tokenized_governance]
path = 'contracts/tokenized_governance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
